### ISSUE TITLE
Problems with flask

### ISSUE THREAD

**Issue by toadlover** [AnonGuy/groupme-discord#7]
I'm not very experienced with python, which is probably attributing to my problems. I am currently unable to get past the final step, where I run the "python3 main.py" command. I know nothing about flasks, and am struggling to understand them in trying to look them up. This is the error that is being thrown:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import web_server
  File "/home/user/groupme-discord/web_server.py", line 7, in <module>
    from flask import Flask, request
ModuleNotFoundError: No module named 'flask'

As extra context, I am operating on a Linux virtual machine. I have also gone the ngrok route regarding flasks. I have the forwarding link from ngrok as the callback URL, and ran the command "./ngrok http 5000"

Any insight for fixing my errors would be greatly appreciated!

**Comment by jerbob** [comment]
Hi @toadlover, thanks for using groupme-discord!

It looks like you haven't installed the dependencies. Make sure you're in the root directory of the project:
```bash
python3 -m pip install -r requirements.txt
```
